CREATE TABLE IF NOT EXISTS order_item(
	id SERIAL PRIMARY KEY,
	order_id INTEGER NOT NULL REFERENCES orders(id),
	product_id INTEGER NOT NULL REFERENCES products(id),
	quantity INTEGER NOT NULL,
	price INTEGER NOT NULL
	)